lib/client/meta_field.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/meta_field_mapper.rb
Add additional support for setting custom meta fields
=> feat(client/*,agent,mapper/*): Add support for metafields

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/modifier_mapper.rb, lib/mapper/product_mapper.rb
set default variant to accuman product isdefault
https://trello.com/c/JZbfs5a8/98-usbat-see-the-product-search-category-listing-as-designed
=> feat(product_agent, modifier_mapper, product_mapper):set default variant

lib/abstract_client.rb, lib/client/custom_field.rb, lib/client/product.rb, lib/client/product_option.rb, lib/client/product_option_value.rb, lib/client/product_variant.rb, lib/client/variant.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/custom_field_mapper.rb, lib/mapper/option_mapper.rb, lib/mapper/option_value_mapper.rb, lib/mapper/product_mapper.rb, lib/mapper/variant_mapper.rb
@mrogers-5s , I think I've done most of the scaffolding work, however I haven't run or tested it at all. I'll try to pick it up next week, but I might need to hand it off to you. I'll let you know if I do.
=> feat(BigcommerceProductAgent): enable product creation as Variants

lib/mapper/variant_mapper.rb
map isbn to correct location on variant product
=> bug(variant_mapper): isbn map to correct location on variant

lib/client/product.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/product_mapper.rb
change digital wrapper sku to be default sku on product -W
=> feat(product, bigcommerce_product_agent, product_mapper): wrapper sku

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/variant_mapper.rb
list of not purchasable fields get set to disable purchasable field
=> feat(variant_mapper, bigcommerce_product_agent): list of not purchasable

lib/mapper/product_mapper.rb
description and meta description are null instead of empty which was
breaking the BC upsert so if they exist then choose that if not make it
empty string
=> bug(product_mapper): description and meta description null

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
fix error causing agent not to work
=> bug(bigcommerce_product_agent): error causing agent not to work

lib/mapper/product_mapper.rb
update availability on products
=> feat(product_mapper): update availability on products

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
@mrogers-5s Would you please review?
=> feat(huginn_bigcommerce_product_agent.rb): disambiguate products by listing product types in name

lib/client/variant.rb
@molenchuk Would you please review?
=> feat(variant.rb): log payload of errors in variants

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
only try to delete meta field if meta field exists
=> fix(bigcommerce_product_agent): only try to delete something if exists

lib/mapper/variant_mapper.rb
update msrp as default price on variants
=> feat(variant_mapper): update msrp on variants

lib/mapper/product_mapper.rb
get categories after splitting into digital and physcial products
=> fix(product_mapper): get categories after splitting into dig and phy

lib/client/meta_field.rb
Fix an error in the handling of meta field IDs during update requests.
https://trello.com/c/PxliWN4A/386-asbat-see-meta-fields-update-correctly
=> fix(client/meta_field): Fix metafield upsert

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/product_mapper.rb
Modify the upsert process to physically delete inactive products rather than just disabling them.
https://trello.com/c/iK0KP8wo/396-usnbat-see-products-that-are-inactive
=> feat(big_commerce_product_agent): delete inactive products

lib/mapper/product_mapper.rb
update inventory tracking for physical products
=> feat(product_mapper): update inventory tracking for physical products

lib/client/product.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/product_mapper.rb
Consolidate API requests and fetch BigCommerce data in bulk when possible to imrpve agent
performance
https://trello.com/c/RNH9chb1/402-asbat-see-all-products-in-the-admin-panel
=> fix(client/product,bigcommerce_product_agent): Consolidate API requests

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
check if product is available for purchase before upserting
=> bug(bigcommerce_product_agent): check if product is available

lib/client/meta_field.rb, lib/client/product.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/custom_field_mapper.rb
Improve the execution speed of this agent and condense BigCommerce API calls where possible
https://trello.com/c/J0mpZADG/412-asbat-see-the-sync-run-faster
=> fix(big_commerce_product_agent): Improve agent execution speed

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
Improve the error handling for batch upserts
https://trello.com/c/kYrw0qwW/426-asbat-see-useful-errors-when-sync-processes-fail
=> fix(bigcommerce_product_agent): improve error handling for upserts

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
Fix an issue in error payload handling that incorrectly submitted huginn event payloads as
BigCommerce API requests.
https://trello.com/c/Ducu00tJ/429-asbat-see-products-created-without-error
=> fix(big_commerce_product_agent): fix handling of error events

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/product_mapper.rb
Add additional option to control inventory tracking so that tracking can be turned off in test
environments
https://trello.com/c/zli6XKAH/435-asbat-see-inventory-tracking-turned-off-in-staging
=> feat(big_commerce_product_agent): Support conditional inventory tracking

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/product_mapper.rb
Fix an error tied to product availability that incorrectly enabled products that should be disabled
https://trello.com/c/tEulLhCD/433-usbat-see-correct-product-availability
=> fix(bigcommerce_product_agent): Change handling of product availability

lib/mapper/product_mapper.rb
update upc field in BC to isbn on acumen product
=> bug(product_mapper): update upc field in BC to isbn on acumen product

lib/mapper/product_mapper.rb
=> bug(product_mapper): update gtin

lib/client/product.rb
=> bug(client/product): return sku

lib/client/custom_field.rb, lib/client/meta_field.rb, lib/client/product.rb, lib/huginn_bigcommerce_product_agent.rb, lib/huginn_bigcommerce_product_agent/big_commerce_product_error.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
Streamline error handling/logging to reduce the strain on the system when things go wrong. Trim
excess data from log messages and focus on the details that actually _matter_
https://trello.com/c/8ICjTqbl/507-dsbat-see-better-error-handling
=> feat(BigCommerceProductError): Streamline error handling/logging

lib/client/custom_field.rb, lib/client/meta_field.rb, lib/client/product.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
Change how we process Faraday errors to account for discrepancies between documentation and what the
error actually exposes to us
https://trello.com/c/8ICjTqbl/507-dsbat-see-better-error-handling
=> fix(error handling): Fix Faraday response processing

lib/client/product.rb
=> bug(product): lookup sku one at a time

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb, lib/mapper/product_mapper.rb
update inventory tracking condition
=> bug(mapper/product_mapper): update inventory tracking condition

lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
=> bug(bigcommerce_product_agent): track inventory fix

lib/client/product.rb, lib/huginn_bigcommerce_product_agent/bigcommerce_product_agent.rb
=> bug(product.rb/ bigcommerce_product_agent): fix error logging bug

lib/mapper/product_mapper.rb
=> fix(product_mapper): check if bc_product exists
